version: '3.8'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=cinematrix
      - MYSQL_USER=cinematrix
      - MYSQL_PASSWORD=cinematrix
      - MYSQL_ROOT_PASSWORD=cinematrix
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - mysql-cinematrix:/var/lib/mysql
    healthcheck:
      test: mysql -h 127.0.0.1 -u cinematrix --password=cinematrix
      start_period: 1s
      interval: 2s
      timeout: 5s
      retries: 10

volumes:
  mysql-cinematrix:
