name: Node.js CI

on:
  push:
    branches: [ release, main ]
  pull_request:
    branches: [ release, main, feature-CM-1 ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Build stack
        run: docker compose up --wait
      - run: cp .env.example .env
      # - run: 
      # - name: Sleep for 5 seconds
      #   uses: jakejarvis/wait-action@master
      #   with:
      #     time: '5s'

      - run: npm test